# Generated by Django 6.0.1 on 2026-01-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
